### ISSUE TITLE
date_change_quote & cancel_quote

### ISSUE THREAD

**Issue by Gwillink** [CurrencyCloud/currencycloud-js#12]
Dear dev team,
Can you add the API endpoints for date_change_quote and cancel_quote for conversions.
Thanks.

**Comment by derikvercueil** [comment]
@Gwillink ,
Thank you for your feedback. This will be added in the next release of the SDK which is currently being finalised.

**Comment by EAddario** [comment]
Fix in PR #13

**Comment by EAddario** [comment]
Fixed in v1.23.2
