### ISSUE TITLE
Transaction Sender

### ISSUE THREAD

**Issue by Gwillink** [CurrencyCloud/currencycloud-js#16]
Dear Dev team,

Please can you include the following api in the next release:

GET https://api.currencycloud.com/v2/transactions/sender/{SENDER_ID}

**Comment by EAddario** [comment]
Hi @Gwillink, this is being addressed with PR #18 

We plan to merge all outstanding PRs within the next two weeks at which point a new release will be available

**Comment by EAddario** [comment]
Fixed in v1.23.2
