### ISSUE TITLE
[SyntaxError: Unexpected token <]

### ISSUE THREAD

**Issue by artsyca** [CurrencyCloud/currencycloud-js#2]
Steps to reproduce:
Happens occasionally when pulling from the `rates` endpoint using the node package. Instead of receiving rates we experience the error

```
[SyntaxError: Unexpected token <]
```

Desired behaviour:
If the error does happen, it would be good to see the payload that caused it. I suspect it's html being returned by the server?

It seems these are not `APIErrors` because we are using `toYAML()`. 

Are you able to provide any insight into these errors and how we can output more information about them?

**Comment by euqen** [comment]
I faced with this issue today when rates endpoint was returning 500 status code. When it started to return 200 status code, this issue also stopped reproducing anymore.

**Comment by eXeDK** [comment]
Any updates on this?

**Comment by artsyca** [comment]
This is caused by html being returned by the API. This happens on rare occasions due to service interruptions or other unexpected errors.

**Comment by eXeDK** [comment]
Are you not planning to fix it?!

**Comment by eXeDK** [comment]
Have you heard from CC if they will fix this issue or are this repo more or less dead?

**Comment by liamm** [comment]
Hi @eXeDK - from following the thread it seems this happens only when the API throws up an unexpected response.  I will add this issue to our development team's backlog for it to be investigated &x addressed in a future sprint.

In the meanwhile, if you have any examples of the API not responding correctly please feel free to contact us with the details.  We also welcome pull requests on our SDKs, so if you have any suggested improvements feel free to contribute.

Cheers,

Liam.
