### ISSUE TITLE
TypeError on payments.delete

### ISSUE THREAD

**Issue by mattpocock** [CurrencyCloud/currencycloud-js#40]
Getting a `TypeError: errorMessages[field] is not iterable` when I call `payments.delete` and receive an error message.

Looks to be an issue with how error.js handles 400 errors.

**Comment by jonathancouchman** [comment]
@mattpocock can you give any details of the actual error response body when you are seeing this issue?

**Comment by jonathancouchman** [comment]
OK, I have managed to reproduce the issue

**Comment by jonathancouchman** [comment]
https://github.com/CurrencyCloud/currencycloud-js/pull/41

**Comment by jonathancouchman** [comment]
Fixed in release 3.4.1 
https://github.com/CurrencyCloud/currencycloud-js/releases/tag/v3.4.1
