### ISSUE TITLE
API integration issue

### ISSUE THREAD

**Issue by songjiahong** [CurrencyCloud/currencycloud-js#57]
We've stuck on integrating the currency cloud api into our backend api.

We are using AWS API gateway + lambda + currency-cloud(v4.0.4) + nodejs12.x as our backend restful API.

Attached the two files related to currency cloud API as your reference, and the logs from the lambda function is:
`START RequestId: d9e31686-70ba-4786-a05c-f6b59dad5840 Version: $LATEST
2021-03-08T12:00:44.333Z	d9e31686-70ba-4786-a05c-f6b59dad5840	INFO	validateCCBeneficiary ...
2021-03-08T12:00:44.333Z	d9e31686-70ba-4786-a05c-f6b59dad5840	INFO	CCFunc start login ...
END RequestId: d9e31686-70ba-4786-a05c-f6b59dad5840
REPORT RequestId: d9e31686-70ba-4786-a05c-f6b59dad5840	Duration: 30030.43 ms	Billed Duration: 30000 ms	Memory Size: 1024 MB	Max Memory Used: 111 MB	
2021-03-08T12:01:14.363Z d9e31686-70ba-4786-a05c-f6b59dad5840 Task timed out after 30.03 seconds`

From the logs, we can see that the login never success at all. And we did try a few ways:

- Change the code from async/await to promise style, like .then(...) -- NO lucky
- Add the package dependencies in the currency cloud js lib to our package.json -- NO lucky
- To simply call login and logout in our API code, and the error is slightly different as follow
The simple code is like:
`currencyCloud.authentication.login({
        environment: process.env.CC_ENV,
        loginId: process.env.CC_ID,
        apiKey: process.env.CC_KEY
      }).then(() => {
        console.log('cc login success');
        currencyCloud.authentication.logout();
      })`

`START RequestId: 3d1103fa-58ff-4026-a3fe-c57a001dee98 Version: $LATEST
2021-03-15T07:57:13.020Z	3d1103fa-58ff-4026-a3fe-c57a001dee98	INFO	validateCCBeneficiary ...
2021-03-15T07:57:13.112Z	3d1103fa-58ff-4026-a3fe-c57a001dee98	INFO	TypeError: Cannot read property 'then' of undefined
    at Runtime.beneficiary_validateBeneficiary [as handler] (/var/task/src/handlers/webpack:/src/handlers/beneficiary.js:61:5)
    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)
2021-03-15T07:57:13.113Z	3d1103fa-58ff-4026-a3fe-c57a001dee98	INFO	TypeError: Cannot read property 'then' of undefined
    at Runtime.beneficiary_validateBeneficiary [as handler] (/var/task/src/handlers/webpack:/src/handlers/beneficiary.js:61:5)
    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)
END RequestId: 3d1103fa-58ff-4026-a3fe-c57a001dee98
REPORT RequestId: 3d1103fa-58ff-4026-a3fe-c57a001dee98	Duration: 135.06 ms	Billed Duration: 136 ms	Memory Size: 1024 MB	Max Memory Used: 106 MB	Init Duration: 723.40 ms	`

[cc.zip](https://github.com/CurrencyCloud/currencycloud-js/files/6152532/cc.zip)

**Comment by songjiahong** [comment]
And this is the testing data using to validate the beneficiary:
`
const data = {
	countryCode: "AU",
	name: "Hotel Global",
	address: "38 An Road",
	city: "Sydney",
	state: "New South Wales",
	email: "admin@hotel.com.au",
	bankType: "SWIFT",
	alwaysSendEmail: true,
	uniquePayId: "",
	reference: "",
	accountNumber: "63332288",
	hasCorrespondentInfo: false,
	permanentRef: false,
	isCafx: false,
	postcode: "2000",
	registerDate: "2021-03-01",
	bankCountryCode: "AU",
	currencyCode: "AUD",
	bankName: "CBA",
	bankAddress: "38 An Road",
	swift: "CTBAAU2S",
	companyId: 1,
	userId: "1dbf18cb-0286-4b7e-ac01-fe6a6e49d04f"
};

const isEmpty = (value) => {
  return value == null || value.length === 0;
};

const convertBeneficiary = (data, validateOnly = false) => {
  let beneficiary = {
    beneficiaryEntityType: 'company',
    beneficiaryCompanyName: data['name'],
    beneficiaryCountry: data['countryCode'],
    currency: data['currencyCode'],
    bankCountry: data['bankCountryCode'],
    accountNumber: data['accountNumber'],
  };
  if (!validateOnly) {
    beneficiary['email'] = data['email'];
    beneficiary['bankAccountHolderName'] = data['name'];
    beneficiary['name'] = data['nickName'];
  }
  if (!isEmpty(data['address'])) beneficiary['beneficiaryAddress'] = data['address'];
  if (!isEmpty(data['bsb'])) {
    beneficiary['routingCodeType1'] = 'bsb_code';
    beneficiary['routingCodeValue1'] = data['bsb'];
  }
  if (!isEmpty(data['swift'])) beneficiary['bicSwift'] = data['swift'];
  if (!isEmpty(data['iban'])) beneficiary['iban'] = data['iban'];
  // if (!isEmpty(data['bankAddress'])) beneficiary['bankAddress'] = data['bankAddress'];
  if (!isEmpty(data['bankName'])) beneficiary['bankName'] = data['bankName'];
  if (!isEmpty(data['city'])) beneficiary['beneficiaryCity'] = data['city'];
  if (!isEmpty(data['postcode'])) beneficiary['beneficiaryPostcode'] = data['postcode'];
  if (!isEmpty(data['state'])) beneficiary['beneficiaryStateOrProvince'] = data['state'];
  if (!isEmpty(data['registerDate'])) beneficiary['beneficiaryDateOfBirth'] = data['registerDate'];
  if (data['bankType'] === 'SWIFT') {
    beneficiary['paymentTypes'] = ['priority'];
  }

  return beneficiary;
}
`

**Comment by jonathancouchman** [comment]
@songjiahong this errors look like "generic" syntax errors. Can I ask whether you been able (or tried) to get the api calls to work outside of AWS and lambda? Have you seen any specific issues with certain API calls, or is it rather you have not been able to get anything to work?

**Comment by songjiahong** [comment]
It's safe to close this issue. Eventually it's the AWS VPC setting which blocks the lambda function to access public internet. Thanks!
