### ISSUE TITLE
Missing the method of validation for payments.

### ISSUE THREAD

**Issue by iHaiduk** [CurrencyCloud/currencycloud-js#59]
In developers docs  currencycloud have a request for validating payment before creating it: https://www.currencycloud.com/developers/docs/item/validate-payment/
But in your library is missing this method

**Comment by jonathancouchman** [comment]
Thank you for reporting this issue.

Adding this missing method is in our backlog to add and we will be looking at it as soon as possible.

**Comment by jonathancouchman** [comment]
payments/validate method has been added in latest release
